dist: bionic
services:
  - docker
language: c

script:
  - if [ -z "$IMG" ]; then docker build --build-arg LIBTPMS_BRANCH=master       --build-arg SWTPM_BRANCH=master       -f ${DOCKERFILE} . || travis_terminate 1; fi
  - if [ -z "$IMG" ]; then docker build --build-arg LIBTPMS_BRANCH=stable-0.7.0 --build-arg SWTPM_BRANCH=stable-0.5   -f ${DOCKERFILE} . || travis_terminate 1; fi
  - if [ -z "$IMG" ]; then docker build --build-arg LIBTPMS_BRANCH=stable-0.7.0 --build-arg SWTPM_BRANCH=stable-0.4   -f ${DOCKERFILE} . || travis_terminate 1; fi
  - if [ -n "$IMG" ]; then docker run --name test --privileged --env LIBTPMS_BRANCH=master       --env SWTPM_BRANCH=master     -v ${PWD}:/test ${IMG} /test/test.$(echo $IMG | tr "/" "-") || travis_terminate 1; fi
  - if [ -n "$IMG" ]; then docker commit test snapshot; docker rm test; export NEW_IMG="snapshot"; fi
  - if [ -n "$IMG" ]; then docker run             --privileged --env LIBTPMS_BRANCH=stable-0.7.0 --env SWTPM_BRANCH=stable-0.5 -v ${PWD}:/test ${NEW_IMG} /test/test.$(echo $IMG | tr "/" "-") || travis_terminate 1; fi
  - if [ -n "$IMG" ]; then docker run             --privileged --env LIBTPMS_BRANCH=stable-0.7.0 --env SWTPM_BRANCH=stable-0.4 -v ${PWD}:/test ${NEW_IMG} /test/test.$(echo $IMG | tr "/" "-") || travis_terminate 1; fi

matrix:
  include:
  - os: linux
    env: DOCKERFILE=Dockerfile.alpine

  - os: linux
    env: DOCKERFILE=Dockerfile.centos

  - os: linux
    env: DOCKERFILE=Dockerfile.centos-8

  - os: linux
    env: IMG=fedora

  - os: linux
    env: DOCKERFILE=Dockerfile.ubuntu

  - os: linux
    env: DOCKERFILE=Dockerfile.debian

  - os: linux
    env: IMG=opensuse/tumbleweed

  - os: linux
    arch: arm64
    env: IMG=fedora

  - os: linux
    arch: ppc64le
    env: IMG=fedora

  - os: linux
    arch: s390x
    env: IMG=fedora
